#!/usr/bin/env python
# -*- coding:utf-8 -*-

db_name_token = 'amazontoken'
db_name_amkiller_us = 'amkiller_us'
db_name_amkiller_jp = 'amkiller_jp'
table_token = 'token'
db_name_task = 'amazontask'
table_sale_task_us = 'sale_task_us'
table_sale_task_jp = 'sale_task_jp'
table_sale_task_status = 'sale_task_status'
table_sale_task_delete_us = 'sale_task_us_delete'
table_sale_task_delete_jp = 'sale_task_jp_delete'
db_name_data_us = 'data_us'
db_name_data_jp = 'data_jp'
db_name_node_info_jp = 'node_info'
db_name_node_info_us = 'node_info_us'
db_name_ip_info_jp = 'ip_info_jp'
db_name_ip_info_us = 'ip_info_us'
table_ip_pool = 'ip_pool'
db_name_rank_task = 'rank_task'
table_rank_task_us = 'task_us'
table_rank_task_jp = 'task_jp'
db_name_rank_data_us = 'rank_data_us'
db_name_rank_data_jp = 'rank_data_jp'
table_rank_data_us = 'data_us'
table_rank_data_jp = 'data_jp'